version: 0.0
os: linux
files:
- source: target/ROOT.war
  destination: /home/ec2-user/javaapp
- source: /scripts/requirements.txt
  destination: /home/ec2-user/scripts
hooks:
  beforeinstall:
    - location: scripts/beforeinstall.sh
      timeout: 2000
      runas: root
  afterInstall:
  - location: scripts/install_python3
    timeout: 2000
    runas: root
  - location: scripts/codestar_remote_access
    timeout: 2000
    runas: root
  - location: scripts/install_java
    timeout: 2000
    runas: root
  - location: scripts/install_tomcat
    timeout: 2000
    runas: root
  - location: scripts/install_httpd
    timeout: 2000
    runas: root
  ApplicationStart:
  - location: scripts/start_server
    timeout: 2000
    runas: root
 ApplicationStop:
  - location: scripts/stop_server
    timeout: 2000
    runas: root

