version: 0.0
os: linux
files:
- source: target/ROOT.war
  destination: /home/ec2-user/javaapp
- source: /scripts/requirements.txt
  destination: /home/ec2-user/scripts
hooks:
  AfterInstall:
  - location: scripts/install_python3
    timeout: 900
    runas: root
  - location: scripts/codestar_remote_access
    timeout: 900
    runas: root
  - location: scripts/install_java
    timeout: 900
    runas: root
  - location: scripts/install_tomcat
    timeout: 900
    runas: root
  - location: scripts/install_httpd
    timeout: 900
    runas: root
  ApplicationStart:
  - location: scripts/start_server
    timeout: 900
    runas: root
 ApplicationStop:
  - location: scripts/stop_server
    timeout: 600
    runas: root


