version: 0.0
os: linux
files:
- source: target/ROOT.war
  destination: /home/ubunut/SampleApp_Linux.zip
- source: /scripts/requirements.txt
  destination: /home/SampleApp_Linux.zip
hooks:
  AfterInstall:
  - location: scripts/install_python3
    timeout: 2000
    runas: root
  - location: scripts/codestar_remote_access
    timeout: 2000
    runas: root
  - location: scripts/install_java
    timeout: 2000
    runas: root
  - location: scripts/install_tomcat
    timeout: 2000
    runas: root
  - location: scripts/install_httpd
    timeout: 2000
    runas: root
  ApplicationStart:
  - location: scripts/start_server
    timeout: 2000
    runas: root
 ApplicationStop:
  - location: scripts/stop_server
    timeout: 2000
    runas: root

